[package]
name = "flarie"
version = "0.1.0"
authors = ["Anthony Oleinik, antholeinik@gmail.com"]
description = "Framework for running rust on cloudflare workers"
readme = "README.md"
keywords = ["cloudflare", "cloudflare workers", "serverless", "framework"]
repository = "https://github.com/antholeole/flarie.git"
documentation = "https://docs.rs/flarie/"
categories = ["web-programming::serverless",
              "cloudflare"]
license = "MIT"
edition = "2018"

[package.metadata.docs.rs]
features = []

[lib]
name = "flarie"
path = "src/lib.rs"

[features]
default = []
