[package]
name = "flarie-entry"
version = "0.3.8"
authors = ["Anthony <antholeinik@gmail.com>"]
description = "entrypoint for the framework"
keywords = ["cloud", "cloudflare"]
repository = "https://github.com/ntex-rs/ntex.git"
license = "MIT"
edition = "2018"

[lib]
name = "flarie"
path = "src/lib.rs"


